= Changelog

== 1.6.0

 * fix: pass the default AWS provider explicitly from tfctl generated configuration.
   This fixes provider inheritance issues when using multiple providers which
   was introduced in 1.3.0.  You may need to add a terraform block with
   `required_provides` to your profiles if you don't have it defined already.
   Terraform will warn about this during `init`.  Here's an example block:

----
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}
----

== 1.5.0

 * feat: support for setting default tags at AWS provider level.  (Thanks @patrickli)
   For details see: https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider
 * feat: new `tf_state_prefix` config parameter. (Thanks @patrickli)
   Allows setting an path prefix for state files stored in S3.
 * feat: print version number in output log

== 1.4.0

 * feat: support yaml anchors and aliases in configuration file.

== 1.3.0

 * feat: support new Terraform provider syntax

BREAKING CHANGE: The minimum supported Terraform version has been bumped to
0.12.29.  If you are running an older version of Terraform you will need to
update to the latest Terraform in 0.12.x series before updating tfctl.  Once
tfctl is updated you can upgrade Terraform to further versions.

== 1.2.2
 * chore: reverted PR #11 - not necessary and introduced regression.  See PR #13 for details.

== 1.2.1
 * chore: added required Ruby version to Gemspec.

== 1.2.0

 * feat: pass TF_ environment variables to terraform (PR #11).

== 1.1.1

 * fix: handle empty response from Organizations API containing children (thanks @grothja)
 * chore: stopped testing on EOL Rubies 2.3 and 2.4 (but should still currently work)
 * chore: dependencies minimum version bump

== 1.1.0

* feat: look for configuration in `tfctl.yaml` by default.

== 1.0.0

* feat(config): JSON schema config validation
* feat(config): added 'data' parameter

BREAKING CHANGE: This release moves user defined data under a separate `data`
parameter so it can be easily distinguished from parameters required by tfctl.
Configuration file will need to be updated to reflect this to pass validation.


== 0.2.0

* feat: configurable Terraform and AWS provider version requirements
* fix: use provider region from config file
* fix: fail when terraform command is missing

== 0.1.0

* feat: Added `-l` switch to list discovered accounts.

== 0.0.2

* fix: Fixed an exception when `exclude_accounts` is not set.

== 0.0.1

* Initial release
