// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: master
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Configuration

toc::[]

== Overview

Tfctl retrieves initial account configuration from AWS Organizations and merges
it with configuration specified in a yaml file (`tfctl.yaml` by default).

The configuration is merged in the following order:

* AWS Organizations data is fetched and stored in an `accounts` array.
* `organization_root` settings are merged with all accounts.
* `organization_units` settings are merged with accounts matching the OU.
* `account_overrides` are merged with individual accounts matching the account name.

Parameters further down the hierarchy take precedence.  For example:

[source, yaml]
----
organization_root:
  data:
    example_param: 'will be overriden further down'

organization_units:
  team:
    data:
      example_param: 'will win in team ou'
  team/live:
    data:
      example_param: 'will win in team/live ou'
----

One exception to this rule is the `profiles` parameter.  Profiles are additive:

[source, yaml]
----
organization_root:
  profiles:
   - profile-one
   - profile-two

organization_units:
  team:
    profiles:
      - profile-three
----

This will result in all three profiles deployed to accounts in `team` OU.

TIP: You can display the fully merged configuration by running `tfctl -s`.
It's safe to run as it doesn't make any changes to AWS resources.  It's a good
way to test your configuration.

== Defining arbitrary data

You can define arbitrary data under the `data:` parameter, both in the root of
the config and in the organization sections.  It will be available in Terraform
profiles to use by your modules.  You can use this to define things like VPC
subnet ranges, s3 bucket names and so on.  `data:` in organization sections
will be merged with accounts following the usual merge order as described
above.

== Handling secrets

No secrets should be committed into Terraform or tfctl configuration.  Use AWS
Secrets Manager instead and retrieve in Terraform profiles using
https://www.terraform.io/docs/providers/aws/d/secretsmanager_secret.html[secrets
manager data source]
