// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: master
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Creating and deploying a tfctl profile

This guide will show you how to create a tfctl profile, declare some resources
in it and deploy it to to a group of accounts in an organization unit.

toc::[]

== Create a new profile

In your tfctl project directory create a new profile:

----
mkdir profiles/example-profile
----

Withing the profile create `data.tf`:

.data.tf
[source, tf]
----
data "aws_caller_identity" "current" {}
----

This file contains Terraform
https://www.terraform.io/docs/configuration/data-sources.html[data source]
declarations.  Data sources are a way of getting data not directly managed in
Terraform into Terraform.  In this case we're using the
https://www.terraform.io/docs/providers/aws/d/caller_identity.html[aws_caller_identity]
.  One of the outputs of this source is `account_id` which will
return the id of the account Terraform is currently running in.

Now create `variables.tf`:

.variables.tf
[source, tf]
----
variable "config" {
  description = "Configuration generated by tfctl in string encoded JSON"
  type = string
}

# local variables
locals {
  # Decode config JSON into a Terraform data structure
  config = jsondecode(var.config)

  # Get current account id from aws_caller_identity data source
  current_account_id = "${data.aws_caller_identity.current.account_id}"

  # Get tfctl configuration for the current account
  current_account_conf = [ for account in local.config["accounts"]: account if account["id"] == local.current_account_id ][0]
}
----

This file contains
https://www.terraform.io/docs/configuration/variables.html[input variables] for
the profile.

The `config` variable is special and must always be declared in a tfctl
profile.  Tfctl configuration can be accessed using this variable. This It
includes an array of all discovered accounts as well their parameters from
tfctl config file.

TIP: You can run `tfctl -c conf/CONFIG_FILE.yaml -s` to show the config data in
yaml format.  This exact data is available in the `config` variable in your
profile.

We also have few https://www.terraform.io/docs/configuration/locals.html[local
variables] in the `locals` block.  We assign the current account id from the
data source we defined previously to `current_account_id`.  This is mainly for
convenience to make the next statement easier to read.  `current_account` loops
over the `config` data and returns configuration for an account which matches
the current account id (i.e. the current account configuration).

Now that we have our data inputs sorted we can start declaring actual AWS
resources to manage.

Create `main.tf`:

.main.tf
[source, tf]
----
resource "aws_s3_bucket" "example" {
  bucket = "tfctl-${local.current_account_conf["name"]}"
  acl    = "private"
}
----

This will create an S3 bucket with a name containing the current account name
(which will vary depending on which account it's deployed to).

== Assign profile to accounts

Before you can deploy the new profile you need to tell `tfctl` which accounts
to deploy it to.

You have few options here:

* deploy to all accounts
* deploy to specific organization unit (OU)
* deploy to individual account


For the sake of this example we're going to deploy our bucket to all accounts
in `test` OU.

In tfctl config file add the profile to the `test` OU:

[source, yaml]
----
organization_units:
  test:
    profiles:
      - example-profile
----


== Plan

To see what would happen when the change is applied run:

----
tfctl -c conf/example.yaml -o test -- init
tfctl -c conf/example.yaml -o test -- plan
----

This will run `terraform init` to initialise terraform and then `terraform
plan` across all accounts in the `test` OU in parallel.  It will display a diff
of changes for each account.

.example terraform plan
----
info: test-example: Terraform will perform the following actions:
info: test-example:
info: test-example:   # module.example-profile.aws_s3_bucket.example will be created
info: test-example:   + resource "aws_s3_bucket" "example" {
info: test-example:       + acceleration_status         = (known after apply)
info: test-example:       + acl                         = "private"
info: test-example:       + arn                         = (known after apply)
info: test-example:       + bucket                      = "tfctl-test-example"
info: test-example:       + bucket_domain_name          = (known after apply)
info: test-example:       + bucket_regional_domain_name = (known after apply)
info: test-example:       + force_destroy               = false
info: test-example:       + hosted_zone_id              = (known after apply)
info: test-example:       + id                          = (known after apply)
info: test-example:       + region                      = (known after apply)
info: test-example:       + request_payer               = (known after apply)
info: test-example:       + website_domain              = (known after apply)
info: test-example:       + website_endpoint            = (known after apply)
info: test-example:
info: test-example:       + versioning {
info: test-example:           + enabled    = (known after apply)
info: test-example:           + mfa_delete = (known after apply)
info: test-example:         }
info: test-example:     }
info: test-example:
info: test-example: Plan: 1 to add, 0 to change, 0 to destroy.
----

If there are errors in your profile, terraform will fail and usually indicate
what went wrong.

tfctl will generate a plan file automatically and use it with `apply` in the
next step.

== Apply

Once you're happy with the plan, apply it.
----
tfctl -c conf/example.yaml -o test -- apply
----
