// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: master
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

== IAM roles

Tfctl usually requires three IAM roles to be configured:

 * `TfctlRole` - read only access to AWS Organizations set up in the primary account.
 * `TerraformStateRole` - access to remote state resources (S3, DynamoDB) in the
    account where your state is stored (can be any account).
 * `TerraformExecutionRole` - configured in all spoke accounts and used for executing Terraform.

The user executing tfctl needs permission to assume all three roles cross
account.  Tfctl will assume roles automatically for you.

It's possible to configure different Terraform execution roles in different
spoke accounts based on OU or account names.  This can be used to restrict
Terraform in certain accounts.

We usually set those roles up using CloudFormation as part of the bootstrapping
process.  See example templates in `examples/bootstrap/`.
